### ISSUE TITLE
Fearfulness and Fearlessness doesn't adjust fright checks

### ISSUE THREAD

**Issue by LanceLake** [richardwilkes/gcs_library#123]
The default in the library under features should be adjusting 1 point per level to fright checks (up or down). Currently, it does not do this.

**Comment by richardwilkes** [comment]
Fearlessness already had the +1 per level. Fearfulness did not, so fixed that. Also added a prerequisite to Fearlessness that you not have Fearfulness as well. Fearfulness already had a similar check.
