### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by tiagoaquinofl** [richardwilkes/gcs_library#128]
Two mispellings
Panhandling default; "Fast Talk" instead of Fast-Talk.
Saber dafult: "Shortswort" instead of Shortsword

**Comment by richardwilkes** [comment]
Please state which file the issue was in

**Comment by tiagoaquinofl** [comment]
basic set master library
![image](https://user-images.githubusercontent.com/37239892/83411618-fcf9e180-a3ee-11ea-884e-6ad0e72f5c49.png)
![image](https://user-images.githubusercontent.com/37239892/83411666-11d67500-a3ef-11ea-9c1f-cb95f684d157.png)

**Comment by tiagoaquinofl** [comment]
just opened the basic set skill files to seek some other mistakes..here it goes:
Artist, Specialization Painting: Last default: "Artsit"
