### ISSUE TITLE
Question: could you provide the schemas for xml library files?

### ISSUE THREAD

**Issue by eugenio** [richardwilkes/gcs_library#3]
As per title, could you provide the schemas for the various classes of xml library files? Or at least tell if all file of each class (traits, skills, equipment, etc ) follow the same schema and which of the file in each class has all the schema elements in its structure(so that I can derive a sigle schema for all the files of each class) ?
I would like to map your library in a database for a website I have in construction.

**Comment by richardwilkes** [comment]
There are already xsd files present. I don't personally use them nor update them (they were contributed by someone), but I don't believe the formats have changed since they were created.
