### ISSUE TITLE
Forest Guardian from DFRPG Elf Template has Camouflage misspelled

### ISSUE THREAD

**Issue by ArchonShiva** [richardwilkes/gcs_library#35]

**Comment by richardwilkes** [comment]
All instances of the word **camouflage** are spelled correctly in the data sets.

**Comment by ArchonShiva** [comment]
Just downloaded a new instance to make sure: camoflage .
![screen shot 2018-03-25 at 17 48 43](https://user-images.githubusercontent.com/35904024/37880355-fb5d216c-3054-11e8-9fcf-cdf2fe839bae.png)

**Comment by ArchonShiva** [comment]
Added a comment with a screenshot off a fresh download.

**Comment by richardwilkes** [comment]
Don't know where you're getting that data from, but it is not in the current data set as checked in. It is possible that is in the current release's data files -- I haven't checked.

**Comment by richardwilkes** [comment]
Decided to go check the current release and that does have the bad spelling in it. Anyway, the current data as checked in does not and will be included in the next release, whenever that occurs.

**Comment by ArchonShiva** [comment]
I'm not familiar enough with what's called what, but when I download GCS (for Mac) from gurpscharactersheet, and open the DFRPG race for elf, and double-click on Forest Guardian, I get that.

I thought that was the proper way to get GCS.
