### ISSUE TITLE
Engineer (Automobiles) defaults to Mechanic (Automobiles), not (Automobile)

### ISSUE THREAD

**Issue by ArchonShiva** [richardwilkes/gcs_library#46]
The Basic Set mixes up the singulars and plurals, but at the very least the default in Engineer (Automobiles) should be changed to Mechanic (Automobile), so defaulting works.

**Comment by richardwilkes** [comment]
Fixed in f6dbec2: Change all uses of **automobiles** to **automobile** for consistency.
