### ISSUE TITLE
DFRPG Illusion spell page references

### ISSUE THREAD

**Issue by daliin** [richardwilkes/gcs_library#54]
The following four wizardly spells in Dungeon Fantasy RPG.spl have DFS45 in their page reference field but they are actually on DFS40 in the book:

- Complex Illusion
- Control Illusion
- Dispel Illusion
- Illusion Disguise

I checked the rest of the Illusion spells as well as the healing spells on page 40 and they are all correct.

**Comment by richardwilkes** [comment]
Fixed by commit 30181527f96f62706f7b7765065ea5e50d722330.
