### ISSUE TITLE
Knife/Shortsword in Low-Tech

### ISSUE THREAD

**Issue by Aurelius-Alfa** [richardwilkes/gcs_library#63]
The skill/default levels on knives in Low-Tech (including small knife and large knife) are those of shortswords; while long knife uses knife stats both for its knife and its shortsword attack.

**Comment by richardwilkes** [comment]
There have been several commits related to fixes in knives in the past. Is this still an issue with the latest data (i.e. that from the repo, not what might have been shipped with some version of GCS)?

**Comment by Aurelius-Alfa** [comment]
It appears to be fixed for long knife and other knife-type weapons in the
current version
