### ISSUE TITLE
Please add a possibility to add wildcard skills 

### ISSUE THREAD

**Issue by marinkashilova90** [richardwilkes/gcs_library#64]
I can not add a wildcards. Can you, please, add it to gcs or advice me how to do it. Thanks in advance.

**Comment by ubik2** [comment]
If you look at the Action skills, you'll find some sample wildcard skills there.
To get the pricing correct, set the difficulty to W.

You can also create your own skills library (File > New Skills Library), then add individual skills (Item > New Skill). These can be added to your characters.

If you're trying to have these wildcard skills used by weapon entries, you may need to take some additional steps. Each weapon entry lists its own skills, and while some are set up to use the wildcard skills, not all of them are. If you have a weapon you want to update, you can edit the weapon. For example, if you want your Knife to use the Assassin! wildcard skill, double click the Knife item on your character, click the Defaults tab, then click the "+" entry, select "Skill Named", and enter "Assassin!" in the text box (leaving the Optional Specialization field empty).

**Comment by richardwilkes** [comment]
This appears to have been answered by @ubik2, so I'm closing it. If you are still having problems, please reopen and state what steps you've taken that are failing.
