### ISSUE TITLE
I can't add new "melee weapons" under skills

### ISSUE THREAD

**Issue by chr-a** [richardwilkes/gcs_library#67]
I've already - in older versions of the GCS - added various uses for SUmo Wrestling as "melee weapons, so they show up in the weapons box.
But suddenly I cant do that anymore. When I enter the "melee weapons" tab I'm missing a "+" sign at the side, in order to add new things.

BTW: GCS is super-awesome!

**Comment by richardwilkes** [comment]
Some versions of Windows make that button invisible for some reason. It is still there, where it has always been and can be clicked as normal -- you might have to click around a bit to find it, though. I've spent many hours investigating why that particular graphic fails to be rendered on Windows and have come up empty and have just resigned myself to living with it. :-(

**Comment by chr-a** [comment]
Thanks for a snappy answer

fre. 11. jan. 2019 kl. 16.35 skrev Richard Wilkes <notifications@github.com
