### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by geoidesic** [richardwilkes/gcs_library#72]
A user manual would be really handy. It's not that intuitive to use.
For example... how do I add skills to the character sheet? In fact.. how do I add anything at all to the character sheet?

It looks interesting but I can't figure out how it works.

**Comment by messiahUA** [comment]
If you are talking about UI interaction then anything can be simply dragged-and-dropped.

**Comment by richardwilkes** [comment]
There are multiple ways to add items to the sheet. The most common, as mentioned by @messiahUA above, is to just drag and drop them from one place to the other. You can also select items in a list that you have open, and select "Copy to Character Sheet" from the Item menu. Or hit the command key accelerator for that menu item. Likewise, there are similar commands to apply whole templates that you have open.

Anyway, as far as a user manual -- that's something others will have to provide, as I have exactly zero interest in ever writing a manual.
