### ISSUE TITLE
Printer Options

### ISSUE THREAD

**Issue by JTremain** [richardwilkes/gcs_library#81]
Print option only shows primary physical printer. Is there a way to recognize/print to PDF driver?

**Comment by richardwilkes** [comment]
You can try switching to the native print dialogs (option in the "Output" preference panel).

**Comment by JTremain** [comment]
I figured out what the problem was. For some reason after upgrading to Ubuntu 19.04 the cups driver was not showing the cups-pdf printer so I simply 'sudo apt-get install cups-pdf' and it re-added the PDF printer and is now seen by GCS.
