### ISSUE TITLE
Super Luck issues

### ISSUE THREAD

**Issue by Techhead0** [richardwilkes/gcs_library#89]
Two issues with Super Luck

Problem: Naming it "Luck, Super" creates an incompatibility with Luck, despite the fact Super Luck is explicitly compatible
Fix: Rename to "Super Luck"

Problem: It inherits the modifiers listed for Luck in BS, despite the fact that Active doesn't really jive with Super Luck's "instead of rolling". No explicit word on the other two modifiers
Fix: Remove Active, possibly Defensive and Aspected as well

**Comment by richardwilkes** [comment]
Revised in 483bb81f7018881f42225fef54af3cb051dd460c
