### ISSUE TITLE
A short list of incorrect entries

### ISSUE THREAD

**Issue by Sorenant** [richardwilkes/gcs_library#95]
First of all, I can't thank you enough for maintaining this project, it's a real life saver for me.
I just updated from 4.11.1 to 4.14 and while updating some libraries to match my edited ones, I noticed some incorrect data has been carried on:
Basic Set:
-Damage Resistance gives +1 DR/level to "full body", when it should be "full body except eyes";
-Nictitating Membrane gives no DR, when it should give +1 DR/level to "eyes";
-Enhanced Defenses (Block, Dodge and Parry) is marked as non-leveled, when it should be leveled;
-Fearlessness gives no bonus to "Fright Check", when it should give +1/level.
Power Ups:
-Talent (Artificer) gives +1 to Masonry, Mechanic and Smith skills, when it should give +1/level;
-Talent (Stalker) gives bonus to "Navigation (Land)" skill with any specialization, when it should be "Navigation" skill with "Land" specialization;
-Huge Weapons (ST) costs 2 points/level, when it should cost 1 point/level;
-Shoves and Tackles has the description of Shield-Wall Training.

Not really an error, but here's a few edits I've done and would like to leave as suggestion:
-Instead of "Rank" advantage with "@Type@:@Title" description, I like to change it to "@Type@ Rank" advantage with "@Title@" description;
-Instead of "Ham-Fisted" and "Ham-Fisted (Severe)" advantages, I like to fold them into a leveled one by removing the Severe variant and editing the other to be leveled;
-Instead of "Legal Enforcement Powers" with 3 mutually exclusive modifiers (Cop, FBI, KGB), I like to turn the advantage into a leveled one, remove the modifiers and add "@Description@" to the description;
-Instead of multiple "Injury Tolerance" entries, I like to create a 0 point one with each variant as a modifier.

I think that's all I have, cheers and thank you again for your work.

**Comment by richardwilkes** [comment]
The best way to get these incorporated is to load the latest version of the relevant files, unlock them, make the edits and save, then either attach them to this request or better yet, if you know how to use git and GitHub, make a Pull Request for them.

If not, I'll eventually get around to them, but I rely on the community to provide the data for the most part.

**Comment by Sorenant** [comment]
Unfortunately I don't know how to use Pull Requests, so here's a zip with the fixed trait list. It includes my personal changes I listed in the second part of the post, if it bothers you just tell me and I'll make an archive without it.

[Fixed ADQs.zip](https://github.com/richardwilkes/gcs_library/files/4150850/Fixed.ADQs.zip)

**Comment by richardwilkes** [comment]
Thanks, @Sorenant -- I'll incorporate these changes into the repo once I find a few spare moments.

**Comment by richardwilkes** [comment]
Will be included as part of the next release, whenever that is
