### ISSUE TITLE
Enhanced Parry (@Melee weapon skill@)

### ISSUE THREAD

**Issue by Kanareika** [richardwilkes/gcs_library#96]
In description said, that i should "add manually" bonus to parry with specific weapon, but there is no way to do this. Is it library problem, or GCS itself?

**Comment by richardwilkes** [comment]
That means you need to open up the specific weapon and alter its weapon details.

**Comment by Kanareika** [comment]
Thank you. Somewhat unobvious.

**Comment by richardwilkes** [comment]
Sure. There is no good way to handle such bonuses at the moment, so its a work-around.
