### ISSUE TITLE
Fencing Skill Missing?

### ISSUE THREAD

**Issue by YetiActual** [richardwilkes/gcs_library#97]
Just started playing with gcs and I can't find fencing.  I know I must be missing something.  Any hints?
Thanks.

**Comment by richardwilkes** [comment]
Do you know what book that is in? I've not ever used fencing, so have never looked for it. Anyway, if it isn't there, you'll have to create it yourself, which isn't usually very hard.

**Comment by shawnhcorey** [comment]
Fencing is not a skill in Basic Set. There is Fencing Weapon Skill in 
Martial Arts.
